..\src\STRUCT41.ASO(7) : Error A2151: Unexpected literal found in expression: <abc>
..\src\STRUCT41.ASO(7) : Error A2209: Syntax error: <abc>
..\src\STRUCT41.ASO(8) : Error A2080: Block nesting error: S1
..\src\STRUCT41.ASO(10) : Error A2102: Symbol not defined : E2
..\src\STRUCT41.ASO(15) : Error A2214: Struct alignment must be 1, 2, 4, 8, 16 or 32
..\src\STRUCT41.ASO(18) : Error A2129: number must be a power of 2: 3
..\src\STRUCT41.ASO(21) : Warning A4250: Ignored: NONUNIQUE
..\src\STRUCT41.ASO(24) : Error A2209: Syntax error: ABC
..\src\STRUCT41.ASO(25) : Error A2080: Block nesting error: S6
